#!/bin/bash

SCRIPT_DIR="./scripts"

install_dependencies() {
	    echo "Verificando e instalando dependencias..."
	            ./scripts/check_dependencies.sh
	            }

	            show_success_message() {
	            	    echo "Todas las dependencias instaladas. Usa 'minetty learn <course>' para empezar."
	            	    }

	            	    init_command() {
	            	    	    echo "Iniciando configuración..."
	            	    	        chmod 777 $SCRIPT_DIR/*
	            	    	            install_dependencies
	            	    	                show_success_message
	            	    	                }

	            	    	                case "$1" in
	            	    	                    init)
	            	    	                            init_command
	            	    	                                    ;;
	            	    	                                        *)
	            	    	                                                echo "Comando no reconocido. Usa 'minetty init' para iniciar."
	            	    	                                                        ;;
	            	    	                                                        esac
	            	    }
	            }
}
